language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
- sudo apt-get update -qq

install:
- sudo apt-get install -qq libfreetype6-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
- sudo apt-get install -qq libsdl2-mixer-dev libsdl2-net-dev liblua5.1-0-dev g++-4.8
- sudo apt-get install -qq cppcheck
- export CC="g++-4.8"

script: make travis

after_script: cppcheck --verbose --enable=all --std=posix --quiet `git ls-files src/\*.cpp`

