language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8
- export CC="g++-4.8"

script:
    - make travis
    
