include config/sources
SRC += tests/test1.cpp

INCS = -I/usr/include/lua5.1 -I/usr/include/GL
LIBS = -llua5.1 -lGL -lGLU -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf

CFLAGS += -g -Wall -O0 -std=c++11 ${INCS} ${CPPFLAGS}
LDFLAGS += -g ${LIBS}

CC = g++

OBJ = ${SRC:.cpp=.o}

all: options test

options:
	@echo tests build options:
	@echo "CFLAGS   = ${CFLAGS}"
	@echo "LDFLAGS  = ${LDFLAGS}"
	@echo "CC       = ${CC}"

.cpp.o:
	@echo CC $<
	@${CC} -c ${CFLAGS} $< -o $@

test: ${OBJ}
	@echo runnin CC -o $@
	@${CC} -o $@ ${OBJ} ${CFLAGS} ${LDFLAGS}

clean:
	@echo cleaning
	@rm -f test
	@rm -f src/*.o

.PHONY: all test options clean